//
//  UserDefaultsDef.h
//  PosMini_Iphone
//
//  Created by chinapnr on 13-7-12.
//  Copyright (c) 2013年 chinaPnr. All rights reserved.
//

#ifndef PosMini_Iphone_UserDefaultsDef_h
#define PosMini_Iphone_UserDefaultsDef_h

#define POSMINI_DEFAULT_VALUE @"#"

#define POSMINI_HAVE_READ_LICENSE @"POSMINI_HAVE_READ_LICENSE"

#define KEYCHAIN_SFHF_SERVICE @"KEYCHAIN_SFHF_SERVICE"

#define POSMINI_LOGIN_ACCOUNT @"POSMINI_LOGIN_ACCOUNT"
#define POSMINI_LOGIN_PASSWORD @"POSMINI_LOGIN_PASSWORD"
#define POSMINI_LOGIN_USERNAME @"POSMINI_LOGIN_USERNAME"
#define POSMINI_LOGIN_DATE @"POSMINI_LOGIN_DATE"
#define POSMINI_LOGIN @"POSMINI_LOGIN"

#define POSMINI_CUSTOMER_ID @"POSMINI_CUSTOMER_ID"

#define POSMINI_ACCOUNT_NEED_REFRESH @"POSMINI_ACCOUNT_NEED_REFRESH"
#define POSMINI_ORDER_NEED_REFRESH @"POSMINI_ORDER_NEED_REFRESH"

#define POSMINI_DEVICE_ID @"POSMINI_DEVICE_ID"

#define POSMINI_DELIVERSIGN @"POSMINI_DELIVERSIGN"


#define ACCOUNT_CHECK_BOX @"ACCOUNT_CHECK_BOX"
#define SECRET_CHECK_BOX @"SECRET_CHECK_BOX"

#define NSSTRING_YES @"YES"
#define NSSTRING_NO @"NO"

#endif
